name: ngxs-action-creator

on: [push]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ngxs-action-creator:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Format check
        run: yarn format:check

      - name: Lint check
        run: yarn lint:check

      - name: Spell check
        run: yarn spell:check

      - name: Test
        run: yarn test:check

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
